pimoroni/enviroplus-python

- Makefile
- README.md
- install.sh
- library/README.rst
- library/setup.cfg
- library/setup.py
- uninstall.sh
This PR migrates Enviro+ Python to the new `setup.cfg` approach from  our boilerplate.
Additionally it uses the new `install.sh` which parses `setup.cfg` for dependencies and postinstall commands, intelligently backs up `/boot/config.txt` and lays the groundwork for a more managble installer infrastructure to be hooked by very minimal get.pimoroni.com scripts.
> Switch to v2 installer

- examples/adc.py
- library/enviroplus/gas.py
- library/tests/test_setup.py
Since the `gas` module is the one that initialises and uses the ADC, I've added the ability to configure the gain for, and optionally enable the spare ADC channel so that it can easily be used to read- for example- an analog CO2 sensor.
The new example `adc.py` demonstrates how to use it and the gain can be set to 6.144v, 4.096v, 2.094v, 1.024v, 0.512v or 0.256v to suit a range of sensor types with the best available resolution.
> Add support for breakout ADC channel

- examples/all-in-one-no-pm.py
- examples/all-in-one.py
- examples/luftdaten.py
Added decoding of bytestring to give Python3 compatibility.
Alternatively you could replace the `get_cpu_temperature()` function with 
```python
from gpiozero import CPUTemperature
cpu = CPUTemperature(min_temp=50, max_temp=90)
```
> Python3 compatibility

- examples/all-in-one-no-pm.py
- examples/all-in-one.py
- examples/compensated-temperature.py
- examples/luftdaten.py
allows temperatures to converge a bit faster
> quick temperature measurement fix

- examples/combined.py
Created a new combined.py that is a modification of all-in-one.py. It adds another mode where all EnviroPlus and PMS5003 sensor readings are combined on one screen.
Each variable that is displayed can have custom warning limits assigned which change the color of the text according to a predefined RGB palette. It allows for a quick glance of all sensor readings at once in order to jugde if everything is OK in the air or to quickly pinpoint a sensor reading that requires attention.
In addition, the new combined mode saves each reading as soon as it is received for graphing later. As in all-in-one.py, moving your finger close to the proximity sensor switches the mode.
Photo:
> Added a new combined mode example

- examples/all-in-one.py
The PMS5003 library returns integers as sensor readings. This causes the current formula for colour scaling of the graph to not work properly because of integer division instead of float division. Converting the PMS5003 results from int to float solves the problem.
Before:
After:
> Fixed graphing problem for PMS5003 results

- examples/particulates.py
The PMS5003 seems to buffer unread samples. If you are reading at a lower rate than it takes readings, then a progressively larger delay will occur between changes in actual PM levels and indicated PM levels. 
To see the issue:
1) run this example with the `time.sleep(1)` **included**
2) wait a few minutes
3) burn a piece of paper near the sensor and wait for the reported PM levels to spike
With the sleep included, there is a delay between introducing smoke and seeing reported levels rise (often a few minutes or longer, and can be hours if it has been running for some time). With the sleep removed you will see reported levels update almost immediately.
The correct way to use the sensor is to read as fast as the sensor allows, and not make any assumptions about what rate samples will be …
> Remove inappropriate sleep between reads

- examples/noise-amps-at-freqs.py
- examples/noise-profile.py
- library/enviroplus/noise.py
- library/setup.cfg
After experimenting with capturing and plotting various noise types I've put together a starter library for noise profiling on Enviro+.
To use this code you'll need to:
```
sudo pip3 install sounddevice
sudo pip install sounddevice
sudo apt install libportaudio2
```
TODO:
* Test & get a feel for the results
* ~Add DocStrings~
* Add (optional) compensation for human perception of amplitude at different frequencies
* ~Add dependencies to installer (sounddevice and portaudio `libportaudio2`)~
> Noise library and examples for basic FFT and frequency binning

- examples/all-in-one-no-pm.py
Launching all-in-one-no-pm.py results in an error due to line 57. FontSize should be replaced with the variable font_size, to run line 57 without error.
> Fix launch bug in all-in-one-no-pm.py

- examples/combined.py
`PMS5003` will throw `ReadTimeoutError`s forever if we don't sleep for some arbitrary time before reading it for the first time.
One second seems to be enough, and that is in line with the value in [examples/particulates.py](https://github.com/pimoroni/enviroplus-python/blob/02c9f287f5963f5221b23fb05c2925eb261ca2de/examples/particulates.py#L19)
> Sleep before first PMS5003 reading

- examples/weather-and-light.py
Ensure that the date and time on the display, as well as the sun and moon positions, are based on the time_zone variable, instead of the time zone of the Raspberry Pi
> Address Issue #55

- library/enviroplus/noise.py
- library/tests/conftest.py
- library/tests/test_noise.py
- library/tests/test_setup.py
Add a simple check for #61 regression and fixed the bug.
Additionally dropped the `force_reimport` function in favour of an `autouse` fixture that forces module reimport.
> Catch #61 with tests and fix

- library/setup.cfg
I ran into Issue #63 on Raspberry Pi Zero W, with Raspbian Lite - the install script would fail, and none of the examples would run. 
Adding python-cffi and python3-cffi in the setup.cfg fixed it, and all the examples work now.
> Include python cffi in setup dependencies

- examples/all-in-one.py
- examples/combined.py
Minor fixes to the examples. logging.warn() is deprecated. Also a timeout warning was not being caught in the event the particle sensor is not present.
> Correcting examples

- examples/mqtt-all.py
- library/setup.cfg
Adds a script for publishing data over MQTT. The live data can be viewed using [mqtt explorer](https://mqtt-explorer.com/) (as below) or integrated into any other IOT project. 
One issue is that the script doesn't appear to run when added to crontab, perhaps you can suggest why?
> Adds mqtt example

- install.sh
Fix for the DATESTAMP variable, to show proper file name.
> Minute instead month in backup file name

- README.md
Would like to add the enviroplus_exporter to the user projects section. The enviroplus_exporter is a Prometheus exporter and exposes the enviroplus metrics so they can be scraped with Prometheus.
> Added user project: enviroplus_exporter

- examples/mqtt-all.py
The `mqtt-all.py` example is really well put together. I've added the settings that enable TLS and Username / Password in case people would like to use this with their secure MQTT Brokers.
Example:
`python3 mqtt-all.py --broker localhost --port 8883 --topic enviro --tls --username enviropi --password raspberry`
> Adding Settings for TLS and Username/Password to MQTT Example

- library/enviroplus/gas.py
- library/setup.cfg
Use the auto-detect feature of the ADS1015 library to support reading the gas sensor via an ADS1115.
> Add support for ADS1115

- examples/all-in-one-no-pm.py
- examples/all-in-one.py
- examples/luftdaten.py
After tweaking `compensate-temperature.py` it struck me that arbitrarily changing the source of temperature compensation may adversely affect long term readfings where the user updates their code.
This PR should fix the remaining instances of using a `vcgencmd measure_temp` subprocess in lieu of just reading the appropriate filesystem node, but we should probably merge it cautiously.  FAO @sandyjmacdonald
> Improvements for #28 (Temperature compensation without sub process)

- library/enviroplus/noise.py
- library/tests/test_noise.py
Add the `ada7002` device into the `sounddevice.rec` startup, to avoid trying to record from whatever the default happens to be and failing miserably. (Pulse Audio??)
> Fix audio capture for #91

- examples/mqtt-all.py
Per [the change I suggested to the Pico-based Enviro code](https://github.com/pimoroni/enviro/pull/2), with this change, the MQTT messages will be published with the retain flag set, so that if a consumer is not subscribed, the most recent set of readings can still be read by a future subscriber later. 
This supports the [homebridge-enviroplus plugin](https://github.com/mhawkshaw/homebridge-enviroplus/issues/2#issuecomment-1215872947) better, so that a publication is more likely to exist on the topic even if the Pi with Enviroplus / this example code is not running at the time. 
Additional update to consider would be to align the message data formats between this sample and the newer Enviro product line.
> mqtt-all.py example: use retained publications

- examples/mqtt-all.py
In setting up the PMS5003 sensor to send readings over MQTT to Home Assistant, I noticed there was an ever increasing delay in the sensor readings the longer the device was running. This was confirmed by lighting a match in front of the sensor: if the Raspberry Pi had just been started, the values updated immediately, but if the device had been left on for an hour, the values stopped updating immediately. 
It turns out that if the PMS5003 sensor is not read from continually, it will start to buffer the readings. In the current `mqtt-all.py` script, the main loop waits for the duration of the specified interval (defaults to 5 seconds) each pass through the loop. However the PMS5003 is taking a reading roughly every second or less. This results in the data sent over MQTT being an additional …
> Adjust Script To Prevent PMS Sensor Buffering

- Makefile
- install.sh
- pyproject.toml
- requirements-examples.txt
- tox.ini
1. Sync with latest boilerplate (no longer complains about /boot/config.txt)
2. Move example requirements to `requirements-examples.txt` (needs a library bump so it doesn't pull in ALL THE THINGS)
3. Add `pillow` to example requirements
> Misc boilerplate updates
